[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/gemini"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gemini"
  status = 200
